export { default as Home } from './Home'
export { default as Payment } from './Payment'
export { default as Shop } from './Shop'
export { default as SignUp } from './SignUp'
export { default as Login } from './Login'
export { default as BookingFlight } from './BookingFlight'
export { default as Profile } from './Profile'
export { default as Post} from './Post'
export { default as Flight} from './Flight'
export { default as Airline} from './Airline'
export { default as Airport} from './Airport'
export { default as Dashboard} from './Dashboard'
